services:
  auth:
    build:
      context: ./back/auth
    container_name: auth
    volumes:
      - ./back/auth/:/app/
      - /app/node_modules
  front:
    build:
      args:
        NODE_ENV: ${NODE_ENV:-dev}
      context: ./front
    container_name: front
  nginx:
    image: ghcr.io/max-lt/nginx-jwt-module:latest
    platform: linux/x86_64
    container_name: nginx
    volumes:
      - ./back/gateway/:/etc/nginx/
    links:
      - auth
      - orders
      - livraison
      - kitchen
      - front
    ports:
        - "80:80"
  orders:
    build:
      context: ./back/orders
    container_name: orders
    volumes:
      - ./back/orders/:/app/
      - /app/node_modules
  livraison:
    build:
      context: ./back/livraison
    container_name: livraison
    volumes:
      - ./back/livraison/:/app/
      - /app/node_modules
  kitchen:
    build:
      context: ./back/kitchen
    container_name: kitchen
    volumes:
      - ./back/kitchen/:/app/
      - /app/node_modules

